"""add workspace_invites table

Revision ID: c10ef9948cbc
Revises: f959b868a2d8
Create Date: 2025-11-10 23:52:11.264743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c10ef9948cbc'
down_revision: Union[str, Sequence[str], None] = 'f959b868a2d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace_invites', 'max_uses')
    op.drop_column('workspace_invites', 'expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace_invites', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('workspace_invites', sa.Column('max_uses', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
