"""add_color_palette_table_and_relation

Revision ID: e35472268f8a
Revises: 131d52a56545
Create Date: 2025-11-05 21:37:19.031766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e35472268f8a'
down_revision: Union[str, Sequence[str], None] = '131d52a56545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Сначала создаем таблицу цветов
    op.create_table('color_palettes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('hex_code', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    
    # 2. Добавляем начальные цвета
    color_palettes_table = sa.table('color_palettes',
        sa.column('name', sa.String),
        sa.column('hex_code', sa.String),
        sa.column('is_active', sa.Boolean)
    )
    
    op.bulk_insert(color_palettes_table,
        [
            {'name': 'Светло-серый', 'hex_code': '#f3f3f3', 'is_active': True},
            {'name': 'Персиковый', 'hex_code': '#ffd6a5', 'is_active': True},
            {'name': 'Мятный', 'hex_code': '#caffbf', 'is_active': True},
            {'name': 'Голубой', 'hex_code': '#a0c4ff', 'is_active': True},
            {'name': 'Розовый', 'hex_code': '#ffc6ff', 'is_active': True},
            {'name': 'Светло-желтый', 'hex_code': '#ffffc0', 'is_active': True},
        ]
    )
    
    # 3. Добавляем колонку color_id как NULLABLE сначала
    op.add_column('columns', sa.Column('color_id', sa.Integer(), nullable=True))
    
    # 4. Устанавливаем дефолтный цвет для существующих колонок
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT id FROM color_palettes WHERE name = 'Светло-серый'"))
    default_color_id = result.scalar()
    
    if default_color_id:
        connection.execute(sa.text(f"UPDATE columns SET color_id = {default_color_id} WHERE color_id IS NULL"))
    
    # 5. Теперь делаем колонку NOT NULL
    op.alter_column('columns', 'color_id', nullable=False)
    
    # 6. Создаем foreign key
    op.create_foreign_key(None, 'columns', 'color_palettes', ['color_id'], ['id'])
    # ### end Alembic commands ###
    
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'labels', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'columns', type_='foreignkey')
    op.drop_column('columns', 'color_id')
    op.drop_table('color_palettes')
    # ### end Alembic commands ###
