"""add userWorkspace relation. And user_avatar

Revision ID: f959b868a2d8
Revises: e35472268f8a
Create Date: 2025-11-10 22:29:47.455640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f959b868a2d8'
down_revision: Union[str, Sequence[str], None] = 'e35472268f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column('color_palettes', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'labels', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'workspaces', ['workspaces_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_to'], ['id'])
    op.drop_column('tasks', 'common_id')
    
    op.add_column('user_workspaces', sa.Column('role', sa.String(), nullable=False, server_default='member'))
    op.add_column('user_workspaces', sa.Column('can_create_projects', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_workspaces', sa.Column('can_invite_users', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_workspaces', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
    
    op.add_column('users', sa.Column(
        'avatar_url',
        sa.String(),
        nullable=True,
        server_default='https://example.com/static/default-avatar.png'
    ))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    op.drop_column('user_workspaces', 'created_at')
    op.drop_column('user_workspaces', 'can_invite_users')
    op.drop_column('user_workspaces', 'can_create_projects')
    op.drop_column('user_workspaces', 'role')
    op.add_column('tasks', sa.Column('common_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'labels', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.alter_column('color_palettes', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
